name: flutter_uploader_example
version: 3.0.0-beta.3
description: Demonstrates how to use the flutter_uploader plugin.
publish_to: "none"

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^9.0.0
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  shared_preferences: ^2.5.2
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_uploader:
    path: ../

flutter:
  uses-material-design: true
